"""Add sc_certificate_filename to Beneficiary model

Revision ID: 3b3bafd1e258
Revises: cb15dafd1c31
Create Date: 2025-05-21 14:48:37.962029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3bafd1e258'
down_revision = 'cb15dafd1c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sc_certificate_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.drop_column('sc_certificate_filename')

    # ### end Alembic commands ###
