"""Add AI Architect feature tables

Revision ID: 611aa367109a
Revises: 3b3bafd1e258
Create Date: 2025-05-21 20:32:01.032635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611aa367109a'
down_revision = '3b3bafd1e258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_architect_design')
    op.drop_table('awaas_application')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awaas_application',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('beneficiary_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('application_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('application_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('allocated_fund', sa.FLOAT(), nullable=True),
    sa.Column('plot_address', sa.TEXT(), nullable=True),
    sa.Column('plot_area_sqft', sa.FLOAT(), nullable=True),
    sa.Column('uploaded_plot_image_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_number')
    )
    op.create_table('ai_architect_design',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=False),
    sa.Column('original_plot_image_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('generated_house_style_1', sa.VARCHAR(length=50), nullable=True),
    sa.Column('generated_image_filename_1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('generated_house_style_2', sa.VARCHAR(length=50), nullable=True),
    sa.Column('generated_image_filename_2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('generated_house_style_3', sa.VARCHAR(length=50), nullable=True),
    sa.Column('generated_image_filename_3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('generated_house_style_4', sa.VARCHAR(length=50), nullable=True),
    sa.Column('generated_image_filename_4', sa.VARCHAR(length=255), nullable=True),
    sa.Column('chosen_design_style', sa.VARCHAR(length=50), nullable=True),
    sa.Column('chosen_image_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('exterior_design_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('interior_design_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('blueprint_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('estimated_house_cost', sa.FLOAT(), nullable=True),
    sa.Column('estimated_labour_cost', sa.FLOAT(), nullable=True),
    sa.Column('total_estimated_cost', sa.FLOAT(), nullable=True),
    sa.Column('design_phase_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('submitted_to_admin_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['awaas_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
