"""Add pmay_component column to beneficiary table

Revision ID: 989020149915
Revises: b34d8af204e4
Create Date: 2025-05-23 01:16:38.968430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989020149915'
down_revision = 'b34d8af204e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pmay_component', sa.String(length=10), nullable=True))
        batch_op.drop_column('sgay_component')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sgay_component', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('pmay_component')

    # ### end Alembic commands ###
