"""add allocated_fund to beneficiary table

Revision ID: b34d8af204e4
Revises: 611aa367109a
Create Date: 2025-05-21 20:57:06.154231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34d8af204e4'
down_revision = '611aa367109a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('architect_session')
    op.drop_table('final_design')
    op.drop_table('ai_house_design')
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocated_fund', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.drop_column('allocated_fund')

    op.create_table('ai_house_design',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('architect_session_id', sa.INTEGER(), nullable=False),
    sa.Column('design_style', sa.VARCHAR(length=100), nullable=True),
    sa.Column('generated_image_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('estimated_house_cost', sa.FLOAT(), nullable=True),
    sa.Column('estimated_building_cost', sa.FLOAT(), nullable=True),
    sa.Column('estimated_labour_cost', sa.FLOAT(), nullable=True),
    sa.Column('total_estimated_cost', sa.FLOAT(), nullable=True),
    sa.Column('is_selected_by_user', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['architect_session_id'], ['architect_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_design',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('architect_session_id', sa.INTEGER(), nullable=False),
    sa.Column('selected_ai_house_design_id', sa.INTEGER(), nullable=True),
    sa.Column('exterior_images_urls', sa.TEXT(), nullable=True),
    sa.Column('interior_images_urls', sa.TEXT(), nullable=True),
    sa.Column('blueprint_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('final_estimated_house_cost', sa.FLOAT(), nullable=True),
    sa.Column('final_estimated_building_cost', sa.FLOAT(), nullable=True),
    sa.Column('final_estimated_labour_cost', sa.FLOAT(), nullable=True),
    sa.Column('final_total_estimated_cost', sa.FLOAT(), nullable=True),
    sa.Column('user_comments', sa.TEXT(), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.Column('admin_approval_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('admin_remarks', sa.TEXT(), nullable=True),
    sa.Column('approved_or_rejected_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['architect_session_id'], ['architect_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_ai_house_design_id'], ['ai_house_design.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('architect_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('beneficiary_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('plot_image_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
