"""add phone_number_column_to_user_table

Revision ID: c12682502d73
Revises: 989020149915
Create Date: 2025-05-24 06:43:32.852927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12682502d73'
down_revision = '989020149915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_generated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assigned_district', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_user_phone_number', ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_phone_number', type_='unique')
        batch_op.drop_column('assigned_district')
        batch_op.drop_column('otp_generated_at')
        batch_op.drop_column('otp')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
