"""new changes

Revision ID: cb15dafd1c31
Revises: 
Create Date: 2025-05-21 13:17:48.310265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb15dafd1c31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income_certificate_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('voter_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ration_card_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('additional_comments', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_failed_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_failed_login')
        batch_op.drop_column('login_attempts')

    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.drop_column('additional_comments')
        batch_op.drop_column('ration_card_number')
        batch_op.drop_column('voter_id')
        batch_op.drop_column('income_certificate_filename')

    # ### end Alembic commands ###
